# Generated by Django 6.0.1 on 2026-01-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.CharField(max_length=150)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('specialty', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMealPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_registration', models.CharField(max_length=30, unique=True)),
                ('automation_type', models.CharField(blank=True, choices=[('WEEKDAYS', 'Segunda a Sexta'), ('ALTERNATE', 'Plantonista (dia sim / dia não)')], help_text='Null = sem automação', max_length=15, null=True)),
                ('default_meal_type', models.CharField(blank=True, choices=[('LUNCH', 'Almoço'), ('DINNER', 'Janta')], max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Obrigatório para plantonista', null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('shift', models.CharField(choices=[('DAY', 'Dia'), ('NIGHT', 'Noite')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='sectors.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
