# Generated by Django 5.2.4 on 2026-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0003_alter_academic_id_alter_doctor_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='category',
            field=models.CharField(choices=[('COMMON', 'Aluno Comum'), ('RESIDENT', 'Residente')], default='COMMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='academic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='academicauthorization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeemealpreference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
