# Generated by Django 5.2.4 on 2026-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0005_alter_academic_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicauthorization',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='academicauthorization',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
