# Generated by Django 5.2.4 on 2026-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0006_alter_academicauthorization_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicauthorization',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicauthorization',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
