# Generated by Django 5.2.4 on 2026-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0007_alter_academicauthorization_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='identifier',
            field=models.CharField(default=0, max_length=30, unique=True, verbose_name='Matrícula'),
        ),
    ]
