# Generated by Django 5.2.4 on 2026-03-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0010_alter_academic_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='identifier',
            field=models.CharField(max_length=30, unique=True, verbose_name='Matrícula'),
        ),
    ]
