# Generated by Django 5.2.4 on 2026-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0011_alter_academic_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemealpreference',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
