# Generated by Django 6.0.1 on 2026-02-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(help_text='Data da semana (ex: segunda-feira)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reference_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Almoço'), ('DINNER', 'Jantar')], max_length=10)),
                ('main', models.CharField(max_length=150, verbose_name='Prato principal')),
                ('side', models.CharField(blank=True, max_length=200, verbose_name='Acompanhamentos')),
                ('dessert', models.CharField(blank=True, max_length=100, verbose_name='Sobremesa')),
                ('weekly_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.weeklymenu')),
            ],
            options={
                'unique_together': {('weekly_menu', 'weekday', 'meal_type')},
            },
        ),
    ]
