# Generated by Django 5.2.4 on 2026-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealRequestSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_start', models.TimeField(default='06:00')),
                ('lunch_end', models.TimeField(default='09:00')),
                ('dinner_start', models.TimeField(default='09:30')),
                ('dinner_end', models.TimeField(default='12:00')),
                ('employee_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_type', models.CharField(max_length=20)),
                ('collaborator_name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Almoço'), ('DINNER', 'Jantar')], max_length=20)),
                ('diet_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('identifier', 'meal_type', 'date')},
            },
        ),
    ]
