# Generated by Django 5.2.4 on 2026-03-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('sectors', '0004_alter_sector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_requests', to='sectors.sector'),
        ),
        migrations.AddIndex(
            model_name='mealrequest',
            index=models.Index(fields=['date'], name='meals_mealr_date_22b101_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrequest',
            index=models.Index(fields=['identifier'], name='meals_mealr_identif_5cc5d4_idx'),
        ),
    ]
