# Generated by Django 5.2.4 on 2026-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_types', '0002_diettype_created_at_diettype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diettype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
