# Generated by Django 6.0.1 on 2026-02-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_types', '0003_alter_diettype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diettype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
